const map=L.map('map',{zoomControl:false}).setView([48.0,10.0],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);
const statusEl=document.querySelector('#status'),sheet=document.querySelector('#sheet');let markers=[];let center=[48.0,10.0];
const kmh=v=>v==null?'—':Math.round(v*1.852)+' km/h', metres=v=>v==null?'—':Math.round(v*0.3048).toLocaleString('de-DE')+' m';
function compass(d){if(d==null)return'—';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]+' · '+Math.round(d)+'°'}
function show(a){document.querySelector('#flight').textContent=(a.flight||a.callsign||'Unbekannter Flug').trim();document.querySelector('#reg').textContent=[a.r,a.t].filter(Boolean).join(' · ')||'Keine weiteren Angaben';document.querySelector('#alt').textContent=metres(a.alt_baro==='ground'?0:a.alt_baro);document.querySelector('#speed').textContent=kmh(a.gs);document.querySelector('#heading').textContent=compass(a.track);let r=a.baro_rate;document.querySelector('#rate').textContent=r==null?'—':Math.abs(Math.round(r*.00508*60))+' m/min '+(r>100?'↑':r<-100?'↓':'→');document.querySelector('#tech').textContent='ICAO '+(a.hex||'—')+(a.squawk?' · Squawk '+a.squawk:'');sheet.classList.remove('hidden')}
function draw(list){markers.forEach(m=>map.removeLayer(m));markers=[];for(const a of list){if(a.lat==null||a.lon==null)continue;const icon=L.divIcon({className:'',html:`<div class="plane" style="transform:rotate(${a.track||0}deg)">▲</div>`,iconSize:[24,24],iconAnchor:[12,12]});const m=L.marker([a.lat,a.lon],{icon}).addTo(map).on('click',()=>show(a));markers.push(m)}statusEl.textContent=list.length+' Flugzeuge · live'}
async function load(){const [lat,lon]=center;try{const r=await fetch(`https://api.airplanes.live/v2/point/${lat.toFixed(3)}/${lon.toFixed(3)}/100`);if(!r.ok)throw Error(r.status);const d=await r.json();draw(d.ac||[])}catch(e){statusEl.textContent='Live-Daten derzeit nicht erreichbar';console.warn(e)}}
function locate(){if(!navigator.geolocation){return}statusEl.textContent='Standort wird gesucht…';navigator.geolocation.getCurrentPosition(p=>{center=[p.coords.latitude,p.coords.longitude];map.setView(center,9);load()},()=>{statusEl.textContent='Standort nicht freigegeben · Testgebiet';load()},{enableHighAccuracy:true,timeout:8000})}
document.querySelector('#locate').onclick=locate;document.querySelector('#close').onclick=()=>sheet.classList.add('hidden');map.on('moveend',()=>{const c=map.getCenter();center=[c.lat,c.lng];load()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();setInterval(load,10000);
