const map=L.map('map',{zoomControl:false}).setView([48.0,10.0],7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);
L.control.zoom({position:'bottomright'}).addTo(map);
const statusEl=document.querySelector('#status'),sheet=document.querySelector('#sheet'),notice=document.querySelector('#notice');
let markers=[],center=[48.0,10.0],locationMarker=null,accuracyCircle=null,loading=false,lastLoad=0,lastGood=[];
const kmh=v=>v==null?'—':Math.round(v*3.6)+' km/h';
const metres=v=>v==null?'—':Math.round(v).toLocaleString('de-DE')+' m';
function compass(d){if(d==null)return'—';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]+' · '+Math.round(d)+'°'}
function show(a){document.querySelector('#flight').textContent=(a.flight||a.registration||'Unbekanntes Fluggerät').trim();document.querySelector('#reg').textContent=[a.registration&&('Kennzeichen '+a.registration),a.aircraftType&&('Typ '+a.aircraftType),a.hex&&('ICAO '+a.hex.toUpperCase())].filter(Boolean).join(' · ')||'Keine weiteren Angaben';document.querySelector('#alt').textContent=metres(a.alt);document.querySelector('#speed').textContent=kmh(a.speed);document.querySelector('#heading').textContent=compass(a.track);document.querySelector('#rate').textContent=a.rate==null?'—':Math.abs(Math.round(a.rate*60))+' m/min '+(a.rate>.5?'↑':a.rate<-.5?'↓':'→');document.querySelector('#tech').textContent=a.squawk?'Transpondercode '+a.squawk:'Live-Positionsdaten';sheet.classList.remove('hidden')}
const svgPlane=`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M29 3h6l3 23 19 10v6l-19-4-2 15 8 5v4l-12-2-12 2v-4l8-5-2-15-19 4v-6l19-10z"/></svg>`;
const svgHeli=`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M8 13h48v4H35v8c8 1 14 7 15 15h7v5h-8c-2 7-8 11-16 11H20c-7 0-12-5-12-12 0-8 6-14 14-14h7V17H8zm14 23c-5 0-8 3-8 8 0 4 3 6 7 6h11V36zm16 0v14c4-1 7-4 7-8s-3-6-7-6z"/><path d="M46 24h4v9h-4zM50 27h10v4H50z"/></svg>`;
const svgLight=`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M29 6h6l2 22 20 7v6l-20-2-2 13 8 4v4l-11-2-11 2v-4l8-4-2-13-20 2v-6l20-7z"/></svg>`;
function craftKind(a){const d=(a.description||'').toUpperCase(),t=(a.aircraftType||'').toUpperCase();if(d.includes('ROTOR')||d.includes('HELICOPTER')||/^(R22|R44|R66|EC|H1[2345]|AS3|B06|B4|S76|A109|A139|A169|A189)/.test(t))return'heli';if(d.includes('LIGHT')||d.includes('ULTRALIGHT')||/^(C1|C2|C3|C4|PA|SR2|DA|P28|BE|M20)/.test(t))return'light';return'plane'}
function craftIcon(a){const kind=craftKind(a),svg=kind==='heli'?svgHeli:kind==='light'?svgLight:svgPlane;return L.divIcon({className:'craft-marker',html:`<div class="craft ${kind}" style="transform:rotate(${a.track||0}deg)">${svg}</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
function draw(list,source){lastGood=list;markers.forEach(m=>map.removeLayer(m));markers=[];for(const a of list){if(a.lat==null||a.lon==null)continue;const m=L.marker([a.lat,a.lon],{icon:craftIcon(a),keyboard:false}).addTo(map).on('click',()=>show(a));markers.push(m)}statusEl.textContent=`${list.length} Flugzeuge · ${source}`;notice.classList.add('hiddenNotice')}
async function fetchProxy(){const c=map.getCenter();const u=new URL('https://gregorbuerger--ddcc2c7abcfe11f182391607ee4eb77e.web.val.run/');u.searchParams.set('lat',c.lat.toFixed(4));u.searchParams.set('lon',c.lng.toFixed(4));u.searchParams.set('radius','100');const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('Flight Tracker API '+r.status);const d=await r.json();return{list:(d.ac||[]).map(a=>({hex:a.hex,flight:(a.flight||a.callsign||'').trim(),registration:a.r||'',aircraftType:a.t||'',description:a.desc||'',category:a.category||'',lon:a.lon,lat:a.lat,alt:a.alt_baro==='ground'?0:(a.alt_baro==null?null:a.alt_baro*.3048),speed:a.gs==null?null:a.gs*.514444,track:a.track,rate:a.baro_rate==null?null:a.baro_rate*.00508,squawk:a.squawk})),source:'Live via adsb.lol'} }
async function load(force=false){if(loading)return;if(!force&&Date.now()-lastLoad<7000)return;loading=true;lastLoad=Date.now();statusEl.textContent='Live-Flugzeuge werden geladen…';try{const result=await fetchProxy();draw(result.list,result.source)}catch(e){console.warn(e);statusEl.textContent=lastGood.length?`${lastGood.length} Flugzeuge · letzte Daten`:'Live-Daten nicht erreichbar';notice.textContent=lastGood.length?'Neue Live-Daten sind gerade nicht erreichbar. Die zuletzt geladenen Flugzeuge bleiben sichtbar.':'Die Karte funktioniert, aber die Live-Flugdaten sind gerade nicht erreichbar. Tippe zum erneuten Versuchen.';notice.classList.remove('hiddenNotice')}loading=false}
function setLocation(p){const ll=[p.coords.latitude,p.coords.longitude],acc=p.coords.accuracy||0;center=ll;if(locationMarker)map.removeLayer(locationMarker);if(accuracyCircle)map.removeLayer(accuracyCircle);locationMarker=L.circleMarker(ll,{radius:8,weight:3,color:'#fff',fillColor:'#1677ff',fillOpacity:1}).addTo(map).bindTooltip('Dein Standort');accuracyCircle=L.circle(ll,{radius:acc,weight:1,color:'#1677ff',fillColor:'#1677ff',fillOpacity:.10}).addTo(map);map.setView(ll,10);statusEl.textContent='Standort gefunden · lade Flugzeuge…';setTimeout(()=>load(true),250)}
function locate(){if(!navigator.geolocation){statusEl.textContent='Standort wird von diesem Browser nicht unterstützt';return}statusEl.textContent='Standort wird gesucht…';navigator.geolocation.getCurrentPosition(setLocation,e=>{const msg=e.code===1?'Standortzugriff nicht erlaubt':e.code===2?'Standort nicht verfügbar':'Standortsuche dauerte zu lange';statusEl.textContent=msg;notice.textContent=msg+'. Du kannst die Karte trotzdem verschieben und Live-Daten laden.';notice.classList.remove('hiddenNotice');load(true)},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
document.querySelector('#locate').onclick=locate;document.querySelector('#close').onclick=()=>sheet.classList.add('hidden');notice.onclick=()=>load(true);map.on('moveend',()=>{const c=map.getCenter();center=[c.lat,c.lng];load()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
setTimeout(locate,500);setInterval(()=>{if(document.visibilityState==='visible')load()},30000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load(true)});
