const map=L.map('map',{zoomControl:false}).setView([48.0,10.0],7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);
L.control.zoom({position:'bottomright'}).addTo(map);
const statusEl=document.querySelector('#status'),sheet=document.querySelector('#sheet'),notice=document.querySelector('#notice');
let markers=[],center=[48.0,10.0],locationMarker=null,accuracyCircle=null,loading=false,lastLoad=0;
const kmh=v=>v==null?'—':Math.round(v*3.6)+' km/h';
const metres=v=>v==null?'—':Math.round(v).toLocaleString('de-DE')+' m';
function compass(d){if(d==null)return'—';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]+' · '+Math.round(d)+'°'}
function show(a){document.querySelector('#flight').textContent=(a.flight||'Unbekannter Flug').trim();document.querySelector('#reg').textContent=[a.country,a.hex&&('ICAO '+a.hex.toUpperCase())].filter(Boolean).join(' · ')||'Keine weiteren Angaben';document.querySelector('#alt').textContent=metres(a.alt);document.querySelector('#speed').textContent=kmh(a.speed);document.querySelector('#heading').textContent=compass(a.track);document.querySelector('#rate').textContent=a.rate==null?'—':Math.abs(Math.round(a.rate*60))+' m/min '+(a.rate>.5?'↑':a.rate<-.5?'↓':'→');document.querySelector('#tech').textContent=a.squawk?'Transpondercode '+a.squawk:'Live-Positionsdaten';sheet.classList.remove('hidden')}
function draw(list,source){markers.forEach(m=>map.removeLayer(m));markers=[];for(const a of list){if(a.lat==null||a.lon==null)continue;const icon=L.divIcon({className:'',html:`<div class="plane" style="transform:rotate(${a.track||0}deg)">▲</div>`,iconSize:[24,24],iconAnchor:[12,12]});const m=L.marker([a.lat,a.lon],{icon}).addTo(map).on('click',()=>show(a));markers.push(m)}statusEl.textContent=`${list.length} Flugzeuge · ${source}`;notice.classList.add('hiddenNotice')}
function fromOpenSky(s){return{hex:s[0],flight:(s[1]||'').trim(),country:s[2],lon:s[5],lat:s[6],alt:s[7]??s[13],speed:s[9],track:s[10],rate:s[11],squawk:s[14]}}
async function fetchOpenSky(){const b=map.getBounds();const pad=.15;const u=new URL('https://opensky-network.org/api/states/all');u.searchParams.set('lamin',Math.max(-90,b.getSouth()-pad));u.searchParams.set('lomin',Math.max(-180,b.getWest()-pad));u.searchParams.set('lamax',Math.min(90,b.getNorth()+pad));u.searchParams.set('lomax',Math.min(180,b.getEast()+pad));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('OpenSky '+r.status);const d=await r.json();return(d.states||[]).map(fromOpenSky)}
async function fetchAirplanes(){const c=map.getCenter();const r=await fetch(`https://api.airplanes.live/v2/point/${c.lat.toFixed(3)}/${c.lng.toFixed(3)}/100`,{cache:'no-store'});if(!r.ok)throw Error('Airplanes.live '+r.status);const d=await r.json();return(d.ac||[]).map(a=>({hex:a.hex,flight:(a.flight||a.callsign||'').trim(),country:a.r||a.t||'',lon:a.lon,lat:a.lat,alt:a.alt_baro==='ground'?0:(a.alt_baro==null?null:a.alt_baro*.3048),speed:a.gs==null?null:a.gs*.514444,track:a.track,rate:a.baro_rate==null?null:a.baro_rate*.00508,squawk:a.squawk}))}
async function load(force=false){if(loading)return;if(!force&&Date.now()-lastLoad<7000)return;loading=true;lastLoad=Date.now();statusEl.textContent='Live-Flugzeuge werden geladen…';let errors=[];for(const src of [{name:'Airplanes.live',fn:fetchAirplanes},{name:'OpenSky',fn:fetchOpenSky}]){try{const list=await src.fn();draw(list,src.name);loading=false;return}catch(e){errors.push(String(e));console.warn(e)}}statusEl.textContent='Live-Daten nicht erreichbar';notice.textContent='Die Karte funktioniert, aber der Browser konnte beide Live-Datenquellen nicht erreichen. Tippe zum erneuten Versuchen.';notice.classList.remove('hiddenNotice');loading=false}
function setLocation(p){const ll=[p.coords.latitude,p.coords.longitude],acc=p.coords.accuracy||0;center=ll;if(locationMarker)map.removeLayer(locationMarker);if(accuracyCircle)map.removeLayer(accuracyCircle);locationMarker=L.circleMarker(ll,{radius:8,weight:3,color:'#fff',fillColor:'#1677ff',fillOpacity:1}).addTo(map).bindTooltip('Dein Standort');accuracyCircle=L.circle(ll,{radius:acc,weight:1,color:'#1677ff',fillColor:'#1677ff',fillOpacity:.10}).addTo(map);map.setView(ll,10);statusEl.textContent='Standort gefunden · lade Flugzeuge…';setTimeout(()=>load(true),250)}
function locate(){if(!navigator.geolocation){statusEl.textContent='Standort wird von diesem Browser nicht unterstützt';return}statusEl.textContent='Standort wird gesucht…';navigator.geolocation.getCurrentPosition(setLocation,e=>{const msg=e.code===1?'Standortzugriff nicht erlaubt':e.code===2?'Standort nicht verfügbar':'Standortsuche dauerte zu lange';statusEl.textContent=msg;notice.textContent=msg+'. Du kannst die Karte trotzdem verschieben und Live-Daten laden.';notice.classList.remove('hiddenNotice');load(true)},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
document.querySelector('#locate').onclick=locate;document.querySelector('#close').onclick=()=>sheet.classList.add('hidden');notice.onclick=()=>load(true);map.on('moveend',()=>{const c=map.getCenter();center=[c.lat,c.lng];load()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
setTimeout(locate,500);setInterval(()=>load(),15000);
